"""create-user

Revision ID: 350d0c698545
Revises: 
Create Date: 2023-01-15 22:46:59.423523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350d0c698545'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True, unique=True),
    sa.Column('email', sa.String(), nullable=True, unique=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
